export const data = [
  'ectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum ',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam ',
  'Lorem ipsum dolor',
  'Loreoloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dolor sit amet consectetur aduptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dllendus reiciendis dicta unde!',
  'ectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum ',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam ',
  'Lorem ipsum dolor',
  'Loreoloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dolor sit amet consectetur aduptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dllendus reiciendis dicta unde!',
  'ectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum ',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil vel doloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam ',
  'Lorem ipsum dolor',
  'Loreoloremque impedit illum. Quae voluptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dolor sit amet consectetur aduptatum, rerum quis at numquam totam dolorem veritatis, suscipit voluptates, ullam doloremque repellendus reiciendis dicta unde!',
  'Lorem ipsum dllendus reiciendis dicta unde!',
];
